---
-
  hosts: all
  name: "basic stuff"
  sudo: true
  roles:
    - base

  hosts: [ "tag_Name_{{environment}}_web", 192.168.33.10] # tag_name is a function that lookup on ec2 instance name
  name: "Minimal Rails Environment"
  sudo: true
  roles:
    - base
    - nginx_sites: []
      role: nginx
    - postgresql
    - role: deployer
      deploy_user: jenkins
      ssh_key_file: '~/.ssh/jenkins-id-rsa.pub'
    - rbenv:
        env: user
        ruby_version: "2.1.4"
        version: v0.4.0
      rbenv_plugins:
        - name: ruby-build
          repo: "git://github.com/sstephenson/ruby-build.git"
          version: v20141027
      rbenv_users:
        - comment: "Deploy user"
          home: /home/deploy/
          name: deploy
      role: rbenv
    - app_name: '{{app_name}}'
      database:
        password: 123456 # TODO CHANGE IT!
        username: '{{app_name}}'
        name: '{{app_name}}'
        host: localhost
      unicorn:
        worker_process: 2
        preload_app: 'true' # fix for unicorn
      role: app
#    - app
